name: MSVC-Win64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg integrate install
          .\vcpkg\vcpkg install

      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2019buildtools --ignore-checksums
          choco install visualstudio2019-workload-vctools --ignore-checksums

      - name: Set up MSVC
        shell: powershell
        run: |
          $vsInstallPath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
          & "$vsInstallPath\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64

      - name: Configure CMake
        shell: powershell
        run: |
          $vcpkgRoot = "$pwd\vcpkg"
          cmake -B build -S . "-DCMAKE_TOOLCHAIN_FILE=$vcpkgRoot\scripts\buildsystems\vcpkg.cmake"

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: inter-doom-dev-win64.zip
          path: build/src/Release/*.exe
          retention-days: 90
